### ISSUE TITLE
Add QA for BALs

### ISSUE THREAD

**Issue by londumas** [igmhub/desi_QA#9]
Add QA for BALs

**Comment by alxogm** [comment]
@londumas Do you have somebody in mind to work on this? Luz Angela has been working on BALs, and could work on it...

**Comment by londumas** [comment]
@alxogm, Yes I just wanted to list the different QA we need.
I would like to have a beginning QA, so that Luz Angela can take over. What is her github id?
Is there a way to identify which quasar has a BAL or not?

On another note, @alxogm don't hesitate to add other tickets if you think some QA are missing.

**Comment by alxogm** [comment]
@londumas I' sending Luz an email to get her id. It would be great to have an starting point with a bulletlist or some TODO list.  I was precisely starting to talk about this with Luz and Andreu 

Yes, we know exactly which quasar has BAL or not, in the mocks this is saved to the metadata, similarly than for DLAs.  We need to make a new run with BALs, could be in London v4, or whatever version you want, because this was not available when we made the runs in London_v2... We can start by asking Luz to do this.

**Comment by londumas** [comment]
@alxogm, I just added the initial BAL QA to the master, so that Luz can modify it in an branch and do a PR:
https://github.com/igmhub/desi_QA/blob/master/Mocks/QA_BLA.ipynb

**Comment by alxogm** [comment]
Thanks @londumas ! 

One quick suggestion , could you put the instructions to set up the  jupyter environment at NERSC in the readme of desi_QA/Mocks?  So that is easier to see, rather than look for the notebook that has such instructions?  Thanks

**Comment by londumas** [comment]
@alxogm. The instructions are there: QA_plots.ipynb.
I would prefer to save them there or to move to a new notebook, called: how to set up you notebook.
What do you prefer?

**Comment by alxogm** [comment]
Maybe a simple text file is enough: how to set up your notebook.  But I guess anyway is ok, this just need to be done once... it was only so that new users can see what they need to do first, and also takes some time to load the current notebook because of all the plots. Thanks!

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/desi_QA/blob/master/Mocks/QA_BAL.ipynb
